name: 马克喵签到

on:
    workflow_dispatch:
    schedule:
        - cron: "30 04 * * *"
    watch:
        types: [started]

jobs:
    build:
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js 16
              uses: actions/setup-node@v3
              with:
                  node-version: 16
            - name: npm install
              run: |
                  npm install
            - name: "运行【马克喵签到】"
              run: |
                  node Scripts/macat/macat_signin.js
              env:
                  macat: ${{ secrets.macat }}
                  

